config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :order_items
  resources :charges, only: [:new, :create]
  resource :carts, only: [:show]

  get 'pages/contact'
  get 'pages/about'
  get 'pages/menu'
  get 'thanks', to: 'charges#thanks', as: 'thanks'

  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/stripe_tool.rb
#This module takes the Customer and Charge creation logic out of Charges#Create
module StripeTool
  def self.create_customer(email: email, stripe_token: stripe_token)
    Stripe::Customer.create(
      email: email,
      source: stripe_token
    )
  end

  def self.create_charge(customer_id: customer_id, amount: amount, description: description)
    Stripe::Charge.create(
      customer: customer_id,
      amount: amount,
      description: description,
      currency: 'usd'
    )
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  #if there is an order_item, multiply the quantity of order_items by the unit_price and then add everything in
  #the collection
  def subtotal
    order_items.collect { |order_item| order_item.valid? ? (order_item.unit_price * order_item.quantity) : 0 }.sum
  end

  private

  #set the subtotal before the input is saved.
  def set_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    #if the unit_price has been saved in the database
    if persisted?
      #return the unit_price that has been saved
      self[:unit_price]
    #otherwise
    else
      #return the product price
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :amount_to_be_charged
  before_action :set_description

  def new
  end

  def create
    customer = StripeTool.create_customer(email: params[:stripeEmail],
                                          stripe_token: params[:stripeToken])

    charge = StripeTool.create_charge(customer_id: customer.id,
                                      amount: @amount,
                                      description: @description)

    redirect_to thanks_path
    
    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end

  def thanks

  end

  private

  def amount_to_be_charged
    @amount = 5500
  end

  def set_description
    @description = "Thank you for eating our cupcakes."
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.new(order_item_params)
    @order.save
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

  private

  def order_item_params
    params.require(:order_item).permit(:product_id, :quantity)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def menu
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to products_path
    else
      render 'new'
    end
  end

  def show

  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_order
    #if the order_id for this session has been initialized
    if !session[:order_id].nil?
      #find the order_id for the current session
      Order.find(session[:order_id])
    #otherise
    else
      #create a new order
      Order.new
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
#Converts cents to currency for display
module ChargesHelper
  def pretty_amount(amount_in_cents)
    number_to_currency(amount_in_cents / 100)
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_item.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <ul>
    <% @order_items.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<% if @order_items.size > 0 %>
  <% @order_items.each do |item| %>
    <div class="well">
      <div class="row">
        <div class="col-sm-3">
          <h4><%= item.product.title %></h4>
        </div>
        <div class="col-sm-3">
          <p><%= item.product.description %></p>
        </div>
        <div class="col-sm-6">
          <div class="pull-right">
            <%= form_for(item, remote: true) do |f| %>
              <%= f.hidden_field :product_id, value: item.product.id %>
              <h5><%= item.product.price %></h5>

              <div class="form-group">
                <%= f.text_field :quantity, value: item.quantity.to_i, min: 1, class: 'form-control' %>
              </div>

              <div class='btn-group'>
                <%= f.submit "Update quantity", class: "btn btn-primary" %>
                <%= link_to "Delete", item, method: :delete, remote: true, class: "btn btn-danger" %>
                <span>Total Price: <%= item.total_price %></span>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% else %>

<% end %>

app/views/carts/show.html.erb
<div class="cart-item">
  <%= render "carts/cart_item" %>

  <%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= pretty_amount(@amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
 <% end %>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= pretty_amount(@amount) %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= pretty_amount(@amount) %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%= @description %>"
          data-amount="<%= @amount %>"
          data-locale="auto"></script>
<% end %>

app/views/charges/thanks.html.erb
<h2>Thanks, you paid <strong><%= pretty_amount(@amount) %></strong>!</h2>

app/views/layouts/_cart.html.erb
<%= link_to carts_path, class: "nav-item nav-link text-white shopping-cart" do %>
  <%= image_tag("shopping-cart.png") %>
  <!--span><%= "#{current_order.order_items.size} items @ $#{current_order.subtotal}" %></span-->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">

    <title>Mana Cupcakes | <%= @title %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="/open-iconic/font/css/open-iconic-bootstrap.css" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <!--body>
    <nav class="navbar navbar-expand-lg navbar-light bg-primary">
      <%= link_to "Mana Cupcakes", root_path, class: "navbar-brand text-light" %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <div class="navbar-nav ml-auto">
          <%= link_to "Home", root_path, class: "nav-item nav-link text-light" %>
          <%= link_to "About", pages_about_path, class: "nav-item nav-link text-light" %>
          <%= link_to "Contact", pages_contact_path, class: "nav-item nav-link text-light" %>
          <%= link_to "Menu", pages_menu_path, class: "nav-item nav-link text-light" %>
          <%= render 'layouts/cart' %>
        </div>
      </div>
    </nav-->
    <body class="text-center <%= params[:action] %>">

    <div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
      <header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">Mana Cupcakes</h3>
          <nav class="nav nav-masthead justify-content-center">
            <%= link_to "Home", root_path, class: "nav-item nav-link text-light" %>
            <%= link_to "About", pages_about_path, class: "nav-item nav-link text-light" %>
            <%= link_to "Contact", pages_contact_path, class: "nav-item nav-link text-light" %>
            <%= link_to "Menu", pages_menu_path, class: "nav-item nav-link text-light" %>
            <%= render 'layouts/cart' %>
          </nav>
        </div>
      </header>

      <%= yield %>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Mana Cupcakes, copyright 2018</p>
        </div>
      </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
  alert("Invalid")
<% else %>
  $(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
<% end %>

app/views/order_items/destroy.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/order_items/update.js.erb
$(".cart").html("<%= escape_javascript(render 'layouts/cart') %>")
$(".cart_item").html("<%= escape_javascript(render 'carts/cart_item') %>")

app/views/pages/about.html.erb
<% @title = "About" %>

<main role="main" class="inner cover">
  <h1 class="cover-heading">Some call it art.</h1>
  <p class="lead">At Mana Cupcakes our mission is to provide the most amazing experience
  one can have with a gluten-free cupcake. That means fresh, organic ingredients cheap
  ones with no nutritional value. Our toppings are light and flavorful so you don't need
  to feel guilty while wolfing down one or two (even three) cupcakes. At the end of the
  day you can feel good about yourself while living a little. </p>
</main>

app/views/pages/contact.html.erb
<% @title = "Contact" %>

<main role="main" class="inner cover">
  <h1 class="cover-heading">Simply. Delicious.</h1>
  <p class="lead">Mana Cupcakes are you primary source for cupcakes that are not only light and delicious but gluten free as well.</p>
  <p class="lead">
    <!--a href="" class="btn btn-lg btn-secondary">Try them out!</a-->
    <%= link_to "Try some now!", pages_menu_path, class: "btn btn-lg btn-secondary" %>
  </p>
</main>

app/views/pages/home.html.erb
<% @title = "Home" %>

<main role="main" class="inner cover">
  <h1 class="cover-heading">Simply. Delicious.</h1>
  <p class="lead">Mana Cupcakes are you primary source for cupcakes that are not only light and delicious but gluten free as well.</p>
  <p class="lead">
    <!--a href="" class="btn btn-lg btn-secondary">Try them out!</a-->
    <%= link_to "Try some now!", pages_menu_path, class: "btn btn-lg btn-secondary" %>
  </p>
</main>

app/views/pages/menu.html.erb
<% @title = "Menu" %>
<%#
<h1>Check out these ever lovin cupcakes!</h1>

<% @products.each do |product| >
  <div class="well">
    <div class="row">
      <div class="col-sm-8">
        <h3><%= product.title ></h3>
      </div>
      <div class="col-sm-8">
        <p><%= product.description ></p>
      </div>
      <div class="col-sm-8">
        <div class="pull-right">
          <%= form_for(@order_item, remote: true) do |f| >
            <%= f.hidden_field :product_id, value: product.id >
            <h5><%= product.price ></h5>

            <div class="form-group">
              <%= f.text_field :quantity, value: 1, min: 1, class: 'form-control' >
            </div>

            <%= f.submit "Add to cart", class: 'btn btn-primary btn-sm', remote: true >
          <% end >
        </div>
      </div>
    </div>
  </div>
<% end %>

<main role="main">
     <!--section class="jumbotron text-center"-->
       <div class="container text-center">
         <h1 class="jumbotron-heading">All the cupcakes you will ever need.</h1>
         <p class="lead">1 cupcake = $3, 6 cupcakes = $15, 12 cupcakes = $30</p>
       </div>
     <!--/section-->

     <!--div class="album py-2 bg-dark">
       <div class="container">

         <div class="row"-->
            <div class="card-columns">
             <div class="card box-shadow border-info">
               <%= image_tag("bacon_maple.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Bacon Maple</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("banana_creme.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Banana Creme</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("blueberry_creme.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Blueberry Creme</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>


             <div class="card box-shadow ">
               <%= image_tag("pumpkin_pie.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Pumpkin Pie</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("raspberry_chocolate.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Raspberry Chocolate</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("red_velvet.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Red Velvet</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>


             <div class="card box-shadow ">
               <%= image_tag("strawberry_creme.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Strawberry Creme</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("tiramisu.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Tiramisu</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>

             <div class="card box-shadow ">
               <%= image_tag("triple_chocolate.JPG", class: "card-img-top") %>
               <div class="card-body">
                 <p class="card-text">Triple Chocolate</p>
                 <div class="d-flex justify-content-between align-items-center">
                   <div class="btn-group">
                     <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                     <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                   </div>
                 </div>
               </div>
             </div>
            </div>
         <!--/div>
       </div>
     </div-->

   </main>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form-group">
    <%= f.label :title, "Title" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description, "Description" %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price, "Price" %>
    <%= f.number_field :price, value: 1, class: 'form-control', min: 1 %>
  </div>

  <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/products/edit.html.erb
<h3>Update product</h3>
<%= render 'form' %>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New product", new_product_path %>

<div class="col-md-6 col-offset-3">
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Price</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.price %></td>
          <td><%= link_to "Edit", edit_product_path(product) %></td>
          <td><%= link_to "Delete", product_path(product), method: :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/products/new.html.erb
<h3>Create new product</h3>

<%= render 'form' %>